# Generated by Django 5.0 on 2025-03-20 17:50

import document_processor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to=document_processor.models.document_upload_path
            ),
        ),
    ]
